version: '3.8'

services:

  account-api:
    platform: "linux/amd64"
    build: ./backend/accountAPI
    ports:
      - "8081:8081"

  product-api:
    platform: "linux/amd64"
    build: ./backend/ProductAPI
    ports:
      - "8080:8080"
      
  web:
    platform: "linux/amd64"
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      API_URL: "http://api:8080"
    depends_on:
      - account-api
      - product-api
