name: GitHub Backend Frontend Build
run-name: Backend, Frontend is being run by ${{ github.actor }}
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Set execute permission for mvnw
        working-directory: ./backend/ProductAPI
        run: chmod +x mvnw
      - name: Build with Maven
        working-directory: ./backend/ProductAPI
        run: ./mvnw --batch-mode --update-snapshots package
  build-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build and test
        working-directory: ./frontend
        run: |
          npm ci
          npm run build --if-present
          npm test
